### PR TITLE
Check if mediaError is null.

### PR DESCRIPTION
**Pull request by woutd**
Fixes `TypeError: mediaError is null` in Firefox console.

### CODE REVIEW

**Comment by ruslandinov** [comment]
Hello @woutd , I'm going to close this PR, as it seems to be very outdated, I wasn't able to reproduce the issue. Do you still have this bug?

**Comment by woutd** [comment]
Hello @ruslandinov, I am also unable to reproduce with the latest version.
FYI: the example in README uses Video.js 5.x, but the latest version of the plugin seems to require 6.x. Also, the HLS URL is not working.
Thanks

**Comment by ruslandinov** [comment]
Thanks for the info, the plugin is compatible with videojs 5.x, that's why we keep it in README.
Also, the stream `http://sample.vodobox.net/skate_phantom_flex_4k/skate_phantom_flex_4k.m3u8` works fine on our side, can you double check please.

**Comment by woutd** [comment]
Plugin with Video.js 5.x, I get `TypeError: t.getTech is not a function` on Firefox:
http://wout.master.cdn02.rambla.be/test_videojshls5.html

Plugin with Video.js 6.x, working:
http://wout.master.cdn02.rambla.be/test_videojshls6.html

The example HLS URL does indeed work, must have made a mistake previously, sorry.

**Comment by ruslandinov** [comment]
Thank you, that's a nice catch!

So, I've just released a fix #65 for this, my problem was that I did not actually check the video.js 5.0.0, and starting video.js 5.3.0 it has `videojs.getTech` method, that's why it worked for me.

Anyway, I fixed it and added an explicit error message if neither `videojs.getTech` or `videojs.getComponent` are available, so it should be fine now. Also, updated the video.js urls, and removed not used dependencies.

**Comment by woutd** [comment]
Cool!
As a last minor remark, the example has double `</script>` and no starting `<html>` :-)

**Comment by ruslandinov** [comment]
Nice catch, thank you! :) Fixed it here #66

**Pull request closed without merging**
